services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/MOHAMEDANDELBADEIL/n8n
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: MOHAMEDANDELBADEIL
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Medo@99946022
